--Selection Bound Class
--A bounded area where where a selection can be made. If a mouse click comes out
--of this area, some sort of cancellation will occur. The tile panel will lose visibility if
--clicked outside of its bounded area.
--Date: 01/10/2016
--Author: Johann S. R. Eckman
